version: "3.9"
services:
    back:
        build: ./geek-inn_back
        ports:
            - "8000:8000"
    front:
        build: ./geek-inn_front
        ports:
            - "8080:8080"            